### ISSUE TITLE
文件读取的异常情况

### ISSUE THREAD

**Issue by wfirooooooo** [1u4nx/Py-MapLine#1]
执行过程中出现以下异常:
Traceback (most recent call last):
  File "mapline.py", line 196, in <module>
    for line in f:
  File "/backup/scripts/env3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position xxx: invalid start byte

上网查询发现使用codecs模块能够解决此问题
https://stackoverflow.com/questions/12468179/unicodedecodeerror-utf8-codec-cant-decode-byte-0x9c

**Comment by lu4nx** [comment]
可否提供下报错的文件？看起来应该是文件编码问题。

**Comment by wfirooooooo** [comment]
时间久远了，抱歉没有回复。
